spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: qwer1234
#    initialization-mode: ALWAYS
#    schema: classpath*:database/initDB.sql
#    data: classpath*:database/populateDB.sql
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect