insert into students (first_name, second_name, middle_name, date_of_birth, class_name, limited_health_options, disability, paid_meals, social_help_before) values ('Роман', 'Яковлев', 'Дмитриевич', '2008-05-15', '8 а', FALSE, FALSE, 15, '2022-02-25');
insert into students (first_name, second_name, middle_name, date_of_birth, class_name, limited_health_options, disability, paid_meals, social_help_before) values ('Ольга', 'Кузнецов', 'Андреевна', '2008-02-23', '8 а', TRUE, FALSE, 15, '2022-03-01');
insert into students (first_name, second_name, middle_name, date_of_birth, class_name, limited_health_options, disability, paid_meals, social_help_before) values ('Маргарита', 'Зуева', 'Ивановна', '2008-10-05', '8 а', FALSE, FALSE, 15, '2022-03-03');
insert into students (first_name, second_name, middle_name, date_of_birth, class_name, limited_health_options, disability, paid_meals, social_help_before) values ('Полина', 'Ильина', 'Глебовна', '2008-03-04', '8 а', TRUE, TRUE, 15, '2022-02-27');
insert into students (first_name, second_name, middle_name, date_of_birth, class_name, limited_health_options, disability, paid_meals, social_help_before) values ('Дарья', 'Федотова', 'Тимуровна', '2008-06-21', '8 а', TRUE, FALSE, 15, '2022-02-24');
insert into students (first_name, second_name, middle_name, date_of_birth, class_name, limited_health_options, disability, paid_meals, social_help_before) values ('Лев', 'Воробьев', 'Степанович', '2008-08-14', '8 а', FALSE, FALSE, 15, '2022-03-04');
insert into students (first_name, second_name, middle_name, date_of_birth, class_name, limited_health_options, disability, paid_meals, social_help_before) values ('Фёдор', 'Лазарев', 'Тимофеевич', '2008-11-17', '8 а', TRUE, TRUE, 15, '2022-03-06');
insert into students (first_name, second_name, middle_name, date_of_birth, class_name, limited_health_options, disability, paid_meals, social_help_before) values ('Анастасия', 'Гусева', 'Алиевна', '2008-05-25', '8 а', TRUE, FALSE, 15, '2022-03-08');
insert into students (first_name, second_name, middle_name, date_of_birth, class_name, limited_health_options, disability, paid_meals, social_help_before) values ('Диана', 'Акимова', 'Артёмовна', '2008-09-30', '8 а', FALSE, FALSE, 15, '2022-04-10');
insert into students (first_name, second_name, middle_name, date_of_birth, class_name, limited_health_options, disability, paid_meals, social_help_before) values ('Елисей', 'Наумов', 'Степанович', '2008-09-03', '8 а', FALSE, FALSE, 15, '2022-03-19');
insert into visits (date_of_meals, ate_food, drank_milk, last_update) values ('2022-04-01', TRUE, TRUE, '2022-04-01');
insert into visits (date_of_meals, ate_food, drank_milk, last_update) values ('2022-04-01', TRUE, TRUE, '2022-04-01');
insert into visits (date_of_meals, ate_food, drank_milk, last_update) values ('2022-04-01', TRUE, FALSE, '2022-04-01');
insert into visits (date_of_meals, ate_food, drank_milk, last_update) values ('2022-04-01', TRUE, TRUE, '2022-04-01');
insert into visits (date_of_meals, ate_food, drank_milk, last_update) values ('2022-04-01', TRUE, TRUE, '2022-04-01');
insert into visits (date_of_meals, ate_food, drank_milk, last_update) values ('2022-04-01', TRUE, FALSE, '2022-04-01');
insert into visits (date_of_meals, ate_food, drank_milk, last_update) values ('2022-04-01', TRUE, TRUE, '2022-04-01');
insert into visits (date_of_meals, ate_food, drank_milk, last_update) values ('2022-04-01', TRUE, TRUE, '2022-04-01');
insert into visits (date_of_meals, ate_food, drank_milk, last_update) values ('2022-04-01', FALSE, FALSE, '2022-04-01');
insert into visits (date_of_meals, ate_food, drank_milk, last_update) values ('2022-04-01', TRUE, TRUE, '2022-04-01');